### PR TITLE
Changing module name

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
Nothing wrong with the PR per se, I'm just wondering if we should enable some CI on our fork first? Thoughts?

**Comment by merlin-northern** [comment]
> Nothing wrong with the PR per se, I'm just wondering if we should enable some CI on our fork first? Thoughts?

could we just, for the sake of continuing, merge that, then merge https://github.com/mendersoftware/mender/pull/587 and then get to the CI stuff?

**Comment by oleorhagen** [comment]
> > Nothing wrong with the PR per se, I'm just wondering if we should enable some CI on our fork first? Thoughts?
> 
> could we just, for the sake of continuing, merge that, then merge [mendersoftware/mender#587](https://github.com/mendersoftware/mender/pull/587) and then get to the CI stuff?

I'm a little uncomfortable with it. What is your opinion @kacf

**Comment by merlin-northern** [comment]
> > > Nothing wrong with the PR per se, I'm just wondering if we should enable some CI on our fork first? Thoughts?
> > 
> > 
> > could we just, for the sake of continuing, merge that, then merge [mendersoftware/mender#587](https://github.com/mendersoftware/mender/pull/587) and then get to the CI stuff?
> 
> I'm a little uncomfortable with it. What is your opinion @kacf

ok, so we decided to get the CI in place. can we merge it before I start with the CI?

**Comment by oleorhagen** [comment]
Sure, this can be merged IMO

**Review by alfrunes — APPROVED** [review]

**Comment by merlin-northern** [comment]
thanks @alfrunes thanks @oleorhagen

**Comment by merlin-northern** [comment]
I swear this is the third time I am doing this patch :)

**Pull request merged**
