### PR TITLE
Commenting out not used consts, for OpenSSL v1.1.0 compatibility.

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by lluiscampos** [comment]
We'll decide on this PR after today's Client Team meeting.

**Comment by merlin-northern** [comment]
> We'll decide on this PR after today's Client Team meeting.

fyi @kacf

**Review by ghost — APPROVED** [review]

**Comment by lluiscampos** [comment]
@merlin-northern Sorry I got late to this one. I had a complicated day...

**Comment by lluiscampos** [comment]
@merlin-northern Remember to follow-up with the dependency update in `mender` repo so that we can fix the build error.

**Comment by merlin-northern** [comment]
> @merlin-northern Sorry I got late to this one. I had a complicated day...

it is fine. I know how it is.

**Pull request merged**
