### PR TITLE
MEN-3974

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Review by lluiscampos — COMMENTED** [review]
My concern is that this segfault can happen with production code, not only with this test. The test is anyway skipped in the Debian build with a custom patch, so this PR is yet another workaround then.

Have we figure out something in the underlying code? When I debugged it it was very strange: `conn` was actually `nil`, and that should not be possible!

**Comment by oleorhagen** [comment]
> My concern is that this segfault can happen with production code, not only with this test. The test is anyway skipped in the Debian build with a custom patch, so this PR is yet another workaround then.
> 
I see. The second commit can probably be skipped then.

> Have we figure out something in the underlying code? When I debugged it it was very strange: `conn` was actually `nil`, and that should not be possible!

I was worried at first too, but:

It was because the error was not checked. If `err != nil` => `conn = nil`. So as long as our code does it's error checking properly, this is not an issue.

I added this too the tests also, as an extra: https://github.com/mendersoftware/openssl/pull/33/commits/b0c8095ece6499aa978149e80133477fcc90cf9c

**Comment by oleorhagen** [comment]
Update was simply `gofmt`.

**Comment by lluiscampos** [comment]
> I was worried at first too, but:
> 
> It was because the error was not checked. If `err != nil` => `conn = nil`. So as long as our code does it's error checking properly, this is not an issue.

That makes sense, thanks.

**Review by lluiscampos — APPROVED** [review]

**Comment by oleorhagen** [comment]
@lluiscampos regarding the second commit. Leave it, or remove?

**Comment by lluiscampos** [comment]
@oleorhagen Leave it, it is harmless. I'll remove the other patch from Debian in the next update.

**Pull request merged**
